services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/geo_api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: ${MONGODB_CONNECTION_STRING}
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
